services:
  - type: worker
    name: telegram-userbot
    env: python
    repo: https://github.com/imsoire/tg-userbot-forwarder
    buildCommand: pip install -r requirements.txt
    startCommand: python3 main.py
